version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

environment:
  GH_TOKEN:
    secure: iV9pwoYYPE+tCNwM5PK3DSQJ6u0jXA5rw01wgarmaUcii1lb/x3QqTv6f+22P91J

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build:dist

test: off
